apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraFiles:
      mountPath: /opt/app-root/src
    replicas: 1
    route:
      enabled: true
    extraEnvs:
      secrets:
        - name: github-secret
    dynamicPluginsRoot:
      persistentVolumeClaim:
        claimName: dynamic-plugins-root
        size: 1Gi
        storageClassName: ibmc-file-gold
  database:
    enableLocalDb: true
