apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-plugins-root
  namespace: local-backstage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ibmc-file-gold
  resources:
    requests:
      storage: 1Gi
